### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by chenzhihan-java** [JelinYao/XunboPlayer#2]
大佬这个vs2019编译不了吗显示无法解析外部符号

**Comment by JelinYao** [comment]
自己全部重新编译下。

**Comment by chenzhihan-java** [comment]
大佬这个url在哪里传入啊没找到

**Comment by chenzhihan-java** [comment]
传入

**Comment by chenzhihan-java** [comment]
传入

**Comment by chenzhihan-java** [comment]
传入

**Comment by JelinYao** [comment]
![Uploading image.png…]()

**Comment by chenzhihan-java** [comment]
谢谢大佬我看看

**Comment by chenzhihan-java** [comment]
大佬您这图片加载不了翻墙好像也不行 好像是资源丢失了

**Comment by JelinYao** [comment]
![image](https://user-images.githubusercontent.com/7205249/117119753-148ed680-adc5-11eb-9646-5abdcb1161a3.png)
是挂了，再试一次。你看看打开文件的事件处理函数，相关代码就在那里，参考下。

**Comment by chenzhihan-java** [comment]
好多谢谢大佬我看看
